package com.roborock.springboot.service.domain;

public class SysRoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission_relation.id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission_relation.role_id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission_relation.permission_id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    private String permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission_relation.id
     *
     * @return the value of sys_role_permission_relation.id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission_relation.id
     *
     * @param id the value for sys_role_permission_relation.id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission_relation.role_id
     *
     * @return the value of sys_role_permission_relation.role_id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission_relation.role_id
     *
     * @param roleId the value for sys_role_permission_relation.role_id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission_relation.permission_id
     *
     * @return the value of sys_role_permission_relation.permission_id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission_relation.permission_id
     *
     * @param permissionId the value for sys_role_permission_relation.permission_id
     *
     * @mbg.generated Thu Feb 18 10:29:43 CST 2021
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }
}