package com.roborock.springboot.service.domain;

public class SysUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_relation.id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_relation.user_id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_relation.role_id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_relation.id
     *
     * @return the value of sys_user_role_relation.id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_relation.id
     *
     * @param id the value for sys_user_role_relation.id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_relation.user_id
     *
     * @return the value of sys_user_role_relation.user_id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_relation.user_id
     *
     * @param userId the value for sys_user_role_relation.user_id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_relation.role_id
     *
     * @return the value of sys_user_role_relation.role_id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_relation.role_id
     *
     * @param roleId the value for sys_user_role_relation.role_id
     *
     * @mbg.generated Thu Feb 18 10:28:17 CST 2021
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}