package com.roborock.springboot.service.domain;

import com.roborock.springboot.service.common.domain.BaseEntity;
import lombok.Data;

import javax.persistence.Id;
import java.util.Date;

@Data
public class SysUser extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated Thu Feb 18 10:20:03 CST 2021
     */
    @Id
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account
     *
     * @mbg.generated Thu Feb 18 10:20:03 CST 2021
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbg.generated Thu Feb 18 10:20:03 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated Thu Feb 18 10:20:03 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_login_time
     *
     * @mbg.generated Thu Feb 18 10:20:03 CST 2021
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.enabled
     *
     * @mbg.generated Thu Feb 18 10:20:03 CST 2021
     */
    private boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account_not_locked
     *
     * @mbg.generated Thu Feb 18 10:20:03 CST 2021
     */
    private boolean accountNonLocked;

}